#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /bin/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: assignemt4

depend: assignemt4-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.assignemt4 $(@)

.PHONY: assignemt4
assignemt4:
	@$(MAKE) -f Makefile.assignemt4 all

.PHONY: assignemt4-depend
assignemt4-depend:
	@$(MAKE) -f Makefile.assignemt4 depend

project_name_list:
	@echo assignemt4
